---
ПЕРСОНАЛЬНІ ХАРЧОВІ ЗВИЧКИ ТА ПРАКТИКИ:
  Чи снідаєш ти зазвичай перед тим, як йти до школи:
    Так: :i_1_1
    Ні: :i_1_2
    Чи снідав (ла) ти сьогодні перед школою:
      Так: :i_1_3
      Ні: :i_1_4
      Не знаю: :i_1_5
    О котрій годині ти снідав (ла):
      Між 6.00 та 9.00 годинами: :i_1_6
      Між 9.00 та 12.00 годинами: :i_1_7
      Між 12.00 та 15.00 годинами: :i_1_8
    Де ти снідав (ла):
      Дома: :i_1_9
      В школі: :i_1_10
      Інше: :i_1_11
  Чи обідаєш ти зазвичай:
    Так: :i_2_1
    Ні: :i_2_2
    Чи обідав (ла) ти сьогодні:
      Так: :i_2_3
      Ні: :i_2_4
      Не знаю: :i_2_5
    О котрій годині ти обідав:
      Між 9.00 та 12.00 годинами: :i_2_6
      Між 12.00 та 15.00 годинами: :i_2_7
      Між 15.00 та 18.00 годинами: :i_2_8
    Хто зазвичай готує твій обід:
      Я беру до школи їжу, приготовану моїми батьками вдома: :i_2_9
      Я обідаю вдома після школи: :i_2_10
      Я обідаю у шкільній їдальні: :i_2_11
      Я купую обід з моїх кишенькових грошей: :i_2_12
      Інше: :i_2_13
  Чи вечеряєш ти зазвичай:
    Так: :i_3_1
    Ні: :i_3_2
    Чи вечеряв (ла) ти вчора:
      Так: :i_3_3
      Ні: :i_3_4
      Не знаю: :i_3_5
    О котрій годині ти вечеряв (ла):
      Між 15.00 та 18.00 годинами: :i_3_6
      Між 18.00 та 21.00 годинами: :i_3_7
      Між 21.00 та 24.00 годинами: :i_3_8
    Де ти вечеряв (ла):
      Дома: :i_3_9
      В школі: :i_3_10
      Інше: :i_3_11