---
I. ПЕРСОНАЛЬНІ ХАРЧОВІ ЗВИЧКИ ТА ПРАКТИКИ:
  I.1 Чи снідаєш ти зазвичай перед тим, як йти до школи:
    Так: :i_1_1
    Ні: :i_1_2
    Чи снідав (ла) ти сьогодні перед школою:
      Так: :i_1_3
      Ні: :i_1_4
      Не знаю: :i_1_5
    О котрій годині ти снідав (ла):
      Між 6.00 та 9.00 годинами: :i_1_6
      Між 9.00 та 12.00 годинами: :i_1_7
      Між 12.00 та 15.00 годинами: :i_1_8
    Де ти снідав (ла):
      Дома: :i_1_9
      В школі: :i_1_10
      Інше: :i_1_11
  I.2 Чи обідаєш ти зазвичай:
    Так: :i_2_1
    Ні: :i_2_2
    Чи обідав (ла) ти сьогодні:
      Так: :i_2_3
      Ні: :i_2_4
      Не знаю: :i_2_5
    О котрій годині ти обідав:
      Між 9.00 та 12.00 годинами: :i_2_6
      Між 12.00 та 15.00 годинами: :i_2_7
      Між 15.00 та 18.00 годинами: :i_2_8
    Хто зазвичай готує твій обід:
      Я беру до школи їжу, приготовану моїми батьками вдома: :i_2_9
      Я обідаю вдома після школи: :i_2_10
      Я обідаю у шкільній їдальні: :i_2_11
      Я купую обід з моїх кишенькових грошей: :i_2_12
      Інше: :i_2_13
  I.3 Чи вечеряєш ти зазвичай:
    Так: :i_3_1
    Ні: :i_3_2
    Чи вечеряв (ла) ти вчора:
      Так: :i_3_3
      Ні: :i_3_4
      Не знаю: :i_3_5
    О котрій годині ти вечеряв (ла):
      Між 15.00 та 18.00 годинами: :i_3_6
      Між 18.00 та 21.00 годинами: :i_3_7
      Між 21.00 та 24.00 годинами: :i_3_8
    Де ти вечеряв (ла):
      Дома: :i_3_9
      В школі: :i_3_10
      Інше: :i_3_11
  I.4 Чи їв (їла) ти щось вчора протягом дня поміж основними прийомами їжі:
    Так: :i_4_1
    Ні: :i_4_2
    Не знаю: :i_4_3
    Що ти їв (їла):
      Бутерброди з сиром або ковбасою: :i_4_4
      Сезонні фрукти: :i_4_5
      Випічка: :i_4_6
      Картопляні чіпси, крекери, суха лапша, etc: :i_4_7
      Солодкі газовані напої: :i_4_8
      Фруктові соки: :i_4_9
      Компот: :i_4_10
      Енергетичні напої: :i_4_11
      Чай: :i_4_12
      Кава: :i_4_13
  I.5 Чи використовуєш ти кишенькові гроші для того, щоб купувати їжу:
    Так: :i_5_1
    Ні: :i_5_2
    Я не маю грошей, щоб щось купувати: :i_5_3
    Я роблю це, коли в мене є гроші: :i_5_4
    Вчора протягом дня та вечора чи купував (ла) ти яку-небудь їжу:
      Так: :i_5_5
      Ні: :i_5_6
      В мене не було грошей, щоб щось купувати: :i_5_7
      Не знаю: :i_5_8
    Що саме ти купував (ла):
      Обід у шкільній їдальні: :i_5_9
      Бутерброди з сиром або ковбасою: :i_5_10
      Сезонні фрукти: :i_5_11
      Випічку: :i_5_12
      Солодощі: :i_5_13
      Картопляні чіпси, крекери, суху лапшу, і т.і.: :i_5_14
      Солодкі газовані напої або енергетичні напої: :i_5_15
      Чай або каву: :i_5_16
    Де саме ти купував (ла) найменовану їжу:
      У шкільній їдальні: :i_5_17
      У найближчому магазині: :i_5_18
      На вулиці: :i_5_19
      Інше: :i_5_20
  I.6 Чи пропускав (ла) ти коли-небудь сніданок, обід або вечерю внаслідок відсутньості їжі:
    Так: :i_6_1
    Ні: :i_6_2
    Не знаю: :i_6_3
  I.7 Чи пропускав (ла) ти коли-небудь сніданок, обід або вечерю внаслідок відсутності грошей, щоб купити їжу:
    Так: :i_7_1
    Ні: :i_7_2
    Не знаю: :i_7_3
  I.8 Чи траплялося таке, щоб якась їжа була недоступною тобі внаслідок відсутньості грошей або високої вартості:
    Так: :i_8_1
    Ні: :i_8_2
    Не знаю: :i_8_3
    Яка саме їжа була недоступною:
      Будь-яка: :i_8_4
      М’ясо та м’ясні продукти: :i_8_5
      Риба та морепродукти: :i_8_6
      Молоко та молочні продукти: :i_8_7
      Солодощі та випічка: :i_8_8
      Свіжі фрукти: :i_8_9
      Свіжі овочі: :i_8_10
      Бутильована вода: :i_8_11
  I.9 Що найбільше впливає на вибір їжі, яку ти вживаєш:
    Батьки та сімейні традиції: :i_9_1
    Реклама та засоби масової інформації: :i_9_2
    Шкільні вчителі: :i_9_3
    Шкільні товариші та друзі: :i_9_4
    Я не знаю: :i_9_5
    Інше: :i_9_6
  I.10 Які проблеми зі здоров'ям можуть мати діти, якщо вони не вживають їжу перед відвідуванням школи:
    Поясни: :i_10_1
  I.11 Чому не корисно їсти надто багато солодощів та цукерок:
    Поясни: :i_11_1
  I.12. Чи добре, на твою думку, снідати перед школою:
    Не добре: :i_12_1
    Добре: :i_12_2
    Я не знаю: :i_12_3
  I.13 Чи складно тобі мати сніданок перед школою:
    Не складно: :i_13_1
    Коли як: :i_13_2
    Складно: :i_13_3
  I.14 Наскільки добре, на твою думку, протягом дня мати триразове харчування та перекуски:
    Не добре: :i_14_1
    Добре: :i_14_2
    Я не знаю: :i_14_3
  I.15 Наскільки складно для тебе протягом дня мати триразове харчування та перекуски:
    Не складно: :i_15_1
    Складно: :i_15_2
    Я не знаю: :i_15_3
  I.16 Наскільки добре на твою думку мати різноманітне харчування:
    Не добре: :i_16_1
    Я не знаю: :i_16_2
    Добре: :i_16_3
  I.17 Наскільки складно для тебе мати різноманітне харчування:
    Не складно: :i_17_1
    Складно: :i_17_2
    Я не знаю: :i_17_3
II. РІЗНІ ФОРМИ НЕДОСТАТНОСТІ ХАРЧУВАННЯ:
  II.1. Чи ти знаєш, що таке недоїдання:
    Так: :ii_1_1
    Ні: :ii_1_2
    Не знаю: :ii_1_3
    Що є ознаками недоїдання:
      Нестача енергії/слабкість: :ii_1_4
      Слабкість імунної системи: :ii_1_5
      Хтось дуже тонкий: :ii_1_6
      Діти не ростуть як вони повинні: :ii_1_7
      Інше: :ii_1_8
      Не знаю: :ii_1_9
  II.2. Що є причиною недостатнього харчування дітей:
    Дорослі дають недостатньо їжі: :ii_2_1
    Дорослі не дають смачної їжі: :ii_2_2
    Їжа водяниста, не містить достатньо поживних речовин: :ii_2_3
    Поганий апетит: :ii_2_4
    Хворий не їсть їжу: :ii_2_5
    Інше: :ii_2_6
    Не знаю: :ii_2_7
    Що може бути причиною того, що люди не мають достатньо їжі:
      Дорослі не мають достатньо грошей, щоб придбати їжу: :ii_2_8
      Їжа недоступна: :ii_2_9
      Дорослі не хочуть витрачати гроші на смачу та здорову їжу: :ii_2_10
      Інше: :ii_2_11
      Не знаю: :ii_2_12
  II.3. Хто може допомогти матері визначити, чи її дитина зростає гарно чи ні:
    Лікар або медична сестра в центрі здоров‘я/лікарні: :ii_3_1
    Інше: :ii_3_2
    Не знаю: :ii_3_3
  II.4. Що повинні робити дорослі для попередження недоїдання серед школярів:
    Давати більше їжі дітям: :ii_4_1
    Підвищити частоту прийомів їжі для дітей: :ii_4_2
    Мати сніданок вдома: :ii_4_3
    Мати сніданок в школі: :ii_4_4
    Отримувати обід в школі: :ii_4_5
    Отримувати закуски в школі: :ii_4_6
    Періодично перевіряти зростання: :ii_4_7
    Організовувати медичні огляди в школі: :ii_4_8
    Давати тільки поживну їжу: :ii_4_9
    Давати різноманітну їжу дітям: :ii_4_10
    Інше: :ii_4_11
    Не знаю: :ii_4_12
  II.5. Наскільки імовірно, за твоєю думкою, ти маєш недостатнє харчування:
    Не імовірно: :ii_5_1
    Я не впевнений: :ii_5_2
    Імовірно я перестав рости: :ii_5_3
    Імовірно я втрачаю вагу: :ii_5_4
    Чи можеш ти вказати причину, чому це не імовірно: :ii_5_5
  II.6. Наскільки серйозно впливає недоїдання на твоє здоров‘я:
    Не серйозно: :ii_6_1
    Ти не впевнений: :ii_6_2
    Серйозно: :ii_6_3
    Чи можеш ти вказати причину, чому це не серйозно: :ii_6_4