---
ПЕРСОНАЛЬНІ ХАРЧОВІ ЗВИЧКИ ТА ПРАКТИКИ:
  Чи снідаєш ти зазвичай перед тим, як йти до школи:
    Так: I.1.1
    Ні: I.1.2
    Чи снідав (ла) ти сьогодні перед школою:
      Так: I.1.3
      Ні: I.1.4
      Не знаю: I.1.5
    О котрій годині ти снідав (ла):
      Між 6.00 та 9.00 годинами: I.1.6
      Між 9.00 та 12.00 годинами: I.1.7
      Між 12.00 та 15.00 годинами: I.1.8
    Де ти снідав (ла):
      Дома: I.1.9
      В школі: I.1.10
      Інше: I.1.11
  Чи обідаєш ти зазвичай:
    Так: I.2.1
    Ні: I.2.2
    Чи обідав (ла) ти сьогодні:
      Так: I.2.3
      Ні: I.2.4
      Не знаю: I.2.5
    О котрій годині ти обідав:
      Між 9.00 та 12.00 годинами: I.2.6
      Між 12.00 та 15.00 годинами: I.2.7
      Між 15.00 та 18.00 годинами: I.2.8
    Хто зазвичай готує твій обід:
      Я беру до школи їжу, приготовану моїми батьками вдома: I.2.9
      Я обідаю вдома після школи: I.2.10
      Я обідаю у шкільній їдальні: I.2.11
      Я купую обід з моїх кишенькових грошей: I.2.12
      Інше: I.2.13
  Чи вечеряєш ти зазвичай:
    Так: I.3.1
    Ні: I.3.2
    Чи вечеряв (ла) ти вчора:
      Так: I.3.3
      Ні: I.3.4
      Не знаю: I.3.5
    О котрій годині ти вечеряв (ла):
      Між 15.00 та 18.00 годинами: I.3.6
      Між 18.00 та 21.00 годинами: I.3.7
      Між 21.00 та 24.00 годинами: I.3.8
    Де ти вечеряв (ла):
      Дома: I.3.9
      В школі: I.3.10
      Інше: I.3.11