---
I. ПЕРСОНАЛЬНІ ХАРЧОВІ ЗВИЧКИ ТА ПРАКТИКИ:
  I.1 Чи снідаєш ти зазвичай перед тим, як йти до школи:
    Так: :i_1_1
    Ні: :i_1_2
    Чи снідав (ла) ти сьогодні перед школою:
      Так: :i_1_3
      Ні: :i_1_4
      Не знаю: :i_1_5
    О котрій годині ти снідав (ла):
      Між 6.00 та 9.00 годинами: :i_1_6
      Між 9.00 та 12.00 годинами: :i_1_7
      Між 12.00 та 15.00 годинами: :i_1_8
    Де ти снідав (ла):
      Дома: :i_1_9
      В школі: :i_1_10
      Інше: :i_1_11
  I.2 Чи обідаєш ти зазвичай:
    Так: :i_2_1
    Ні: :i_2_2
    Чи обідав (ла) ти сьогодні:
      Так: :i_2_3
      Ні: :i_2_4
      Не знаю: :i_2_5
    О котрій годині ти обідав:
      Між 9.00 та 12.00 годинами: :i_2_6
      Між 12.00 та 15.00 годинами: :i_2_7
      Між 15.00 та 18.00 годинами: :i_2_8
    Хто зазвичай готує твій обід:
      Я беру до школи їжу, приготовану моїми батьками вдома: :i_2_9
      Я обідаю вдома після школи: :i_2_10
      Я обідаю у шкільній їдальні: :i_2_11
      Я купую обід з моїх кишенькових грошей: :i_2_12
      Інше: :i_2_13
  I.3 Чи вечеряєш ти зазвичай:
    Так: :i_3_1
    Ні: :i_3_2
    Чи вечеряв (ла) ти вчора:
      Так: :i_3_3
      Ні: :i_3_4
      Не знаю: :i_3_5
    О котрій годині ти вечеряв (ла):
      Між 15.00 та 18.00 годинами: :i_3_6
      Між 18.00 та 21.00 годинами: :i_3_7
      Між 21.00 та 24.00 годинами: :i_3_8
    Де ти вечеряв (ла):
      Дома: :i_3_9
      В школі: :i_3_10
      Інше: :i_3_11
  I.4 Чи їв (їла) ти щось вчора протягом дня поміж основними прийомами їжі:
    Так: :i_4_1
    Ні: :i_4_2
    Не знаю: :i_4_3
    Що ти їв (їла):
      Бутерброди з сиром або ковбасою: :i_4_4
      Сезонні фрукти: :i_4_5
      Випічка: :i_4_6
      Картопляні чіпси, крекери, суха лапша, etc: :i_4_7
      Солодкі газовані напої: :i_4_8
      Фруктові соки: :i_4_9
      Компот: :i_4_10
      Енергетичні напої: :i_4_11
      Чай: :i_4_12
      Кава: :i_4_13
  I.5 Чи використовуєш ти кишенькові гроші для того, щоб купувати їжу:
    Так: :i_5_1
    Ні: :i_5_2
    Я не маю грошей, щоб щось купувати: :i_5_3
    Я роблю це, коли в мене є гроші: :i_5_4
    Вчора протягом дня та вечора чи купував (ла) ти яку-небудь їжу:
      Так: :i_5_5
      Ні: :i_5_6
      В мене не було грошей, щоб щось купувати: :i_5_7
      Не знаю: :i_5_8
    Що саме ти купував (ла):
      Обід у шкільній їдальні: :i_5_9
      Бутерброди з сиром або ковбасою: :i_5_10
      Сезонні фрукти: :i_5_11
      Випічку: :i_5_12
      Солодощі: :i_5_13
      Картопляні чіпси, крекери, суху лапшу, і т.і.: :i_5_14
      Солодкі газовані напої або енергетичні напої: :i_5_15
      Чай або каву: :i_5_16
    Де саме ти купував (ла) найменовану їжу:
      У шкільній їдальні: :i_5_17
      У найближчому магазині: :i_5_18
      На вулиці: :i_5_19
      Інше: :i_5_20
  I.6 Чи пропускав (ла) ти коли-небудь сніданок, обід або вечерю внаслідок відсутньості їжі:
    Так: :i_6_1
    Ні: :i_6_2
    Не знаю: :i_6_3
  I.7 Чи пропускав (ла) ти коли-небудь сніданок, обід або вечерю внаслідок відсутності грошей, щоб купити їжу:
    Так: :i_7_1
    Ні: :i_7_2
    Не знаю: :i_7_3
  I.8 Чи траплялося таке, щоб якась їжа була недоступною тобі внаслідок відсутньості грошей або високої вартості:
    Так: :i_8_1
    Ні: :i_8_2
    Не знаю: :i_8_3
    Яка саме їжа була недоступною:
      Будь-яка: :i_8_4
      М’ясо та м’ясні продукти: :i_8_5
      Риба та морепродукти: :i_8_6
      Молоко та молочні продукти: :i_8_7
      Солодощі та випічка: :i_8_8
      Свіжі фрукти: :i_8_9
      Свіжі овочі: :i_8_10
      Бутильована вода: :i_8_11
  I.9 Що найбільше впливає на вибір їжі, яку ти вживаєш:
    Батьки та сімейні традиції: :i_9_1
    Реклама та засоби масової інформації: :i_9_2
    Шкільні вчителі: :i_9_3
    Шкільні товариші та друзі: :i_9_4
    Я не знаю: :i_9_5
    Інше: :i_9_6
  I.10 Які проблеми зі здоров'ям можуть мати діти, якщо вони не вживають їжу перед відвідуванням школи:
    Поясни: :i_10_1
  I.11 Чому не корисно їсти надто багато солодощів та цукерок:
    Поясни: :i_11_1
  I.12. Чи добре, на твою думку, снідати перед школою:
    Не добре: :i_12_1
    Добре: :i_12_2
    Я не знаю: :i_12_3
  I.13 Чи складно тобі мати сніданок перед школою:
    Не складно: :i_13_1
    Коли як: :i_13_2
    Складно: :i_13_3
  I.14 Наскільки добре, на твою думку, протягом дня мати триразове харчування та перекуски:
    Не добре: :i_14_1
    Добре: :i_14_2
    Я не знаю: :i_14_3
  I.15 Наскільки складно для тебе протягом дня мати триразове харчування та перекуски:
    Не складно: :i_15_1
    Складно: :i_15_2
    Я не знаю: :i_15_3
  I.16 Наскільки добре на твою думку мати різноманітне харчування:
    Не добре: :i_16_1
    Я не знаю: :i_16_2
    Добре: :i_16_3
  I.17 Наскільки складно для тебе мати різноманітне харчування:
    Не складно: :i_17_1
    Складно: :i_17_2
    Я не знаю: :i_17_3
II. РІЗНІ ФОРМИ НЕДОСТАТНОСТІ ХАРЧУВАННЯ:
  II.1. Чи ти знаєш, що таке недоїдання:
    Так: :ii_1_1
    Ні: :ii_1_2
    Не знаю: :ii_1_3
    Що є ознаками недоїдання:
      Нестача енергії/слабкість: :ii_1_4
      Слабкість імунної системи: :ii_1_5
      Хтось дуже тонкий: :ii_1_6
      Діти не ростуть як вони повинні: :ii_1_7
      Інше: :ii_1_8
      Не знаю: :ii_1_9
  II.2. Що є причиною недостатнього харчування дітей:
    Дорослі дають недостатньо їжі: :ii_2_1
    Дорослі не дають смачної їжі: :ii_2_2
    Їжа водяниста, не містить достатньо поживних речовин: :ii_2_3
    Поганий апетит: :ii_2_4
    Хворий не їсть їжу: :ii_2_5
    Інше: :ii_2_6
    Не знаю: :ii_2_7
    Що може бути причиною того, що люди не мають достатньо їжі:
      Дорослі не мають достатньо грошей, щоб придбати їжу: :ii_2_8
      Їжа недоступна: :ii_2_9
      Дорослі не хочуть витрачати гроші на смачу та здорову їжу: :ii_2_10
      Інше: :ii_2_11
      Не знаю: :ii_2_12
  II.3. Хто може допомогти матері визначити, чи її дитина зростає гарно чи ні:
    Лікар або медична сестра в центрі здоров‘я/лікарні: :ii_3_1
    Інше: :ii_3_2
    Не знаю: :ii_3_3
  II.4. Що повинні робити дорослі для попередження недоїдання серед школярів:
    Давати більше їжі дітям: :ii_4_1
    Підвищити частоту прийомів їжі для дітей: :ii_4_2
    Мати сніданок вдома: :ii_4_3
    Мати сніданок в школі: :ii_4_4
    Отримувати обід в школі: :ii_4_5
    Отримувати закуски в школі: :ii_4_6
    Періодично перевіряти зростання: :ii_4_7
    Організовувати медичні огляди в школі: :ii_4_8
    Давати тільки поживну їжу: :ii_4_9
    Давати різноманітну їжу дітям: :ii_4_10
    Інше: :ii_4_11
    Не знаю: :ii_4_12
  II.5. Наскільки імовірно, за твоєю думкою, ти маєш недостатнє харчування:
    Не імовірно: :ii_5_1
    Я не впевнений: :ii_5_2
    Імовірно я перестав рости: :ii_5_3
    Імовірно я втрачаю вагу: :ii_5_4
    Чи можеш ти вказати причину, чому це не імовірно: :ii_5_5
  II.6. Наскільки серйозно впливає недоїдання на твоє здоров‘я:
    Не серйозно: :ii_6_1
    Ти не впевнений: :ii_6_2
    Серйозно: :ii_6_3
    Чи можеш ти вказати причину, чому це не серйозно: :ii_6_4
III. НЕДОСТАТНІСТЬ МІКРОНУТРИЄНТІВ:
  III.1. Ти чув що небудь про анемію:
    Так: :iii_1_1
    Ні: :iii_1_2
    Не знаю: :iii_1_3
    Ти можеш описати своїми словами що таке анемія: :iii_1_4
  III.2. Ти чув про залізо в їжі та багаті залізом продукти:
    Так: :iii_2_1
    Ні: :iii_2_2
    Не знаю: :iii_2_3
    Які продукти, багаті залізом, ти знаєш: :iii_2_4
  III.3. Ти чув про вітамін C:
    Так: :iii_3_1
    Ні: :iii_3_2
    Не знаю: :iii_3_3
    Які продукти та напої, багаті на вітамін С, ти знаєш: :iii_3_4
  III.4. Відзнач продукти, які ти їв вчора протягом доби:
    Печінка: :iii_4_1
    Серце: :iii_4_2
    Яловичина: :iii_4_3
    Свинина: :iii_4_4
    Кролик: :iii_4_5
    Курка: :iii_4_6
    Качка: :iii_4_7
    Свіжа риба: :iii_4_8
    Сушена риба: :iii_4_9
    Копчена риба: :iii_4_10
    Маринована риба: :iii_4_11
    Консервована риба: :iii_4_12
    Креветки: :iii_4_13
    Морепродукти: :iii_4_14
    Петрушка: :iii_4_15
    Салат: :iii_4_16
    Гарбузове насіння: :iii_4_17
    Зелений горошок: :iii_4_18
    Буряк: :iii_4_19
    Броколі: :iii_4_20
    Гречка: :iii_4_21
    Ізюм: :iii_4_22
    Сушені абрикоси: :iii_4_23
    Сушені яблука: :iii_4_24
    Сушені сливи: :iii_4_25
    Мигдаль: :iii_4_26
    Помідори: :iii_4_27
  III.5. Ти звичайно їси петрушку, кріп, зелений або червоний перець, свіжі цитрусові, такі як апельсин, лимон та грейпфрут:
    Так: :iii_5_1
    Ні: :iii_5_2
    Не знаю: :iii_5_3
    Ти їси хоч би один з цих продуктів кожен день:
      Так: :iii_5_4
      Ні: :iii_5_5
      Не знаю: :iii_5_6
  III.6. Ти звичайно п‘єш чай або кофе:
    Так: :iii_6_1
    Ні: :iii_6_2
    Не знаю: :iii_6_3
    Ти п‘єш кофе або чай кожен день:
      Так: :iii_6_4
      Ні: :iii_6_5
      Не знаю: :iii_6_6
    Коли ти звичайно п‘єш кофе або чай:
      За дві години до їжі: :iii_6_7
      Одразу перед їжею: :iii_6_8
      Упродовж прийому їжі: :iii_6_9
      Одразу після їжі: :iii_6_10
      Через дві години чи більше після їжі: :iii_6_11
      Інше: :iii_6_12
      Не знаю: :iii_6_13
  III.7. Чи ти звичайно п’єш енергетичні напої:
    Так: :iii_7_1
    Ні: :iii_7_2
    Не знаю: :iii_7_3
    Як часто ти вживаєш енергетичні напої:
      Кожен день: :iii_7_4
      Кілька разів на день: :iii_7_5
      Двічі в неділю: :iii_7_6
      Раз в неділю: :iii_7_7
  III.8. Наскільки тобі подобається смак м‘яса:
    Не подобається: :iii_8_1
    Не впевнений: :iii_8_2
    Подобається: :iii_8_3
  III.9. Наскільки тобі подобається смак риби:
    Не подобається: :iii_9_1
    Не впевнений: :iii_9_2
    Подобається: :iii_9_3
  III.10. Наскільки тобі подобається смак цитрусових фруктів та соків, таких як апельсин, лимон та грейпфрут:
    Не подобається: :iii_10_1
    Не впевнений: :iii_10_2
    Подобається: :iii_10_3
  III.11. Наскільки тобі подобається смак яблук:
    Не подобається: :iii_11_1
    Не впевнений: :iii_11_2
    Подобається: :iii_11_3
  III.12. Ти чув що небудь про вітамін А:
    Так: :iii_12_1
    Ні: :iii_12_2
    Не знаю: :iii_12_3
  III.13. Продукти харчування, багаті на вітамін A, які ти знаєш:
    Напиши: :iii_13_1
  III.14. Які продукти ти їв вчора, протягом для та ввечері:
    Печінка: :iii_14_1
    Серце: :iii_14_2
    Яєчні жовтки: :iii_14_3
    Ікра: :iii_14_4
    Печінка тріски: :iii_14_5
    Молоко, сир, йогурт чи інші молочні продукти: :iii_14_6
    Морква: :iii_14_7
    Гарбуз: :iii_14_8
    Червоний солодкий перець: :iii_14_9
    Салат: :iii_14_10
    Петрушка: :iii_14_11
    Скорботи: :iii_14_12
    Шпинат: :iii_14_13
    Кріп: :iii_14_14
    Зелень бобових: :iii_14_15
    Капуста: :iii_14_16
    Селера: :iii_14_17
    Цибуля: :iii_14_18
    Абрикос: :iii_14_19
    Продукти, збагачені вітаміном A: :iii_14_20
  III.15. Наскільки тобі подобається смак печінки:
    Не подобається: :iii_15_1
    Байдуже: :iii_15_2
    Подобається: :iii_15_3
  III.16. Наскільки тобі подобається смак моркви:
    Не подобається: :iii_16_1
    Байдуже: :iii_16_2
    Подобається: :iii_16_3
  III.17. Наскільки тобі подобається смак гарбуза:
    Не подобається: :iii_17_1
    Байдуже: :iii_17_2
    Подобається: :iii_17_3
  III.18. Твоя мати використовувала сіль для приготування головної страви:
    Так: :iii_18_1
    Ні: :iii_18_2
    Не знаю: :iii_18_3
    Яку саме сіль вона використовувала:
      Йодовану: :iii_18_4
      Не йодовану: :iii_18_5
      Солі дома немає: :iii_18_6
      Не знаю: :iii_18_7
  III.19. Ти чув що небудь про йодну недостатність:
    Так: :iii_19_1
    Ні: :iii_19_2
    Не знаю: :iii_19_3
    Можеш ти описати ознаки йодної недостатності в організмі:
      Апатія: :iii_19_4
      Труднощі з навчанням: :iii_19_5
      Поганий настрій: :iii_19_6
      Інше: :iii_19_7
      Не знаю: :iii_19_8
  III.20. Що спричиняє йодну недостатність:
    Недостатність або відсутність споживання йодованої солі: :iii_20_1
    Недостатність їжі, яка містить йод: :iii_20_2
    Інше: :iii_20_3
    Не знаю: :iii_20_4
  III.21. Як можна попередити йодну недостатність:
    Їсти/готувати страви з йодованою сіллю: :iii_21_1
    Їсти їжу, яка містить йод: :iii_21_2
    Інше: :iii_21_3
    Не знаю: :iii_21_4
  III.22. Наскільки серйозною, за твоєю думкою, є недостатність йоду в організмі:
    Не серйозно: :iii_22_1
    Не впевнений: :iii_22_2
    Серйозно: :iii_22_3
    Напиши, будь ласка, причину, чому це не серйозно: :iii_22_4
  III.23. Наскільки правильно, за твоєю думкою, готувати страви з йодованою сіллю:
    Не правильно: :iii_23_1
    Не впевнений: :iii_23_2
    Правильно: :iii_23_3
    Чи можеш ти вказати причину, чому це не правильно: :iii_23_4