class AddPartIiToQuestionnaires < ActiveRecord::Migration[5.2]
  def change
    add_column :questionnaires, :ii_1_1, :boolean
    add_column :questionnaires, :ii_1_2, :boolean
    add_column :questionnaires, :ii_1_3, :boolean
    add_column :questionnaires, :ii_1_4, :boolean
    add_column :questionnaires, :ii_1_5, :boolean
    add_column :questionnaires, :ii_1_6, :boolean
    add_column :questionnaires, :ii_1_7, :boolean
    add_column :questionnaires, :ii_1_8, :boolean
    add_column :questionnaires, :ii_1_9, :boolean
    add_column :questionnaires, :ii_2_1, :boolean
    add_column :questionnaires, :ii_2_2, :boolean
    add_column :questionnaires, :ii_2_3, :boolean
    add_column :questionnaires, :ii_2_4, :boolean
    add_column :questionnaires, :ii_2_5, :boolean
    add_column :questionnaires, :ii_2_6, :boolean
    add_column :questionnaires, :ii_2_7, :boolean
    add_column :questionnaires, :ii_2_8, :boolean
    add_column :questionnaires, :ii_2_9, :boolean
    add_column :questionnaires, :ii_2_10, :boolean
    add_column :questionnaires, :ii_2_11, :boolean
    add_column :questionnaires, :ii_2_12, :boolean
    add_column :questionnaires, :ii_3_1, :boolean
    add_column :questionnaires, :ii_3_2, :boolean
    add_column :questionnaires, :ii_3_3, :boolean
    add_column :questionnaires, :ii_4_1, :boolean
    add_column :questionnaires, :ii_4_2, :boolean
    add_column :questionnaires, :ii_4_3, :boolean
    add_column :questionnaires, :ii_4_4, :boolean
    add_column :questionnaires, :ii_4_5, :boolean
    add_column :questionnaires, :ii_4_6, :boolean
    add_column :questionnaires, :ii_4_7, :boolean
    add_column :questionnaires, :ii_4_8, :boolean
    add_column :questionnaires, :ii_4_9, :boolean
    add_column :questionnaires, :ii_4_10, :boolean
    add_column :questionnaires, :ii_4_11, :boolean
    add_column :questionnaires, :ii_4_12, :boolean
    add_column :questionnaires, :ii_5_1, :boolean
    add_column :questionnaires, :ii_5_2, :boolean
    add_column :questionnaires, :ii_5_3, :boolean
    add_column :questionnaires, :ii_5_4, :boolean
    add_column :questionnaires, :ii_5_5, :text
    add_column :questionnaires, :ii_6_1, :boolean
    add_column :questionnaires, :ii_6_2, :boolean
    add_column :questionnaires, :ii_6_3, :boolean
    add_column :questionnaires, :ii_6_4, :text
  end
end
