class AddIiiColumnsToQuestionnaires < ActiveRecord::Migration[5.2]
  def change
    add_column :questionnaires, :iii_6_1, :text
    add_column :questionnaires, :iii_8_1, :boolean
    add_column :questionnaires, :iii_8_2, :boolean
    add_column :questionnaires, :iii_8_3, :boolean
    add_column :questionnaires, :iii_8_4, :boolean
    add_column :questionnaires, :iii_8_5, :boolean
    add_column :questionnaires, :iii_8_6, :boolean
    add_column :questionnaires, :iii_9_28, :boolean
    add_column :questionnaires, :iii_9_29, :boolean
    add_column :questionnaires, :iii_9_30, :boolean
    add_column :questionnaires, :iii_9_31, :boolean
    add_column :questionnaires, :iii_13_1, :boolean
    add_column :questionnaires, :iii_13_2, :boolean
    add_column :questionnaires, :iii_13_3, :boolean
    add_column :questionnaires, :iii_13_4, :text
    add_column :questionnaires, :iii_14_1, :boolean
    add_column :questionnaires, :iii_14_2, :boolean
    add_column :questionnaires, :iii_14_3, :boolean
    add_column :questionnaires, :iii_14_4, :text
    add_column :questionnaires, :iii_15_1, :boolean
    add_column :questionnaires, :iii_15_2, :boolean
    add_column :questionnaires, :iii_15_3, :boolean
    add_column :questionnaires, :iii_15_4, :text
    add_column :questionnaires, :iii_16_1, :boolean
    add_column :questionnaires, :iii_16_2, :boolean
    add_column :questionnaires, :iii_16_3, :boolean
    add_column :questionnaires, :iii_16_4, :text
    add_column :questionnaires, :iii_17_1, :boolean
    add_column :questionnaires, :iii_17_2, :boolean
    add_column :questionnaires, :iii_17_3, :boolean
    add_column :questionnaires, :iii_17_4, :text
    add_column :questionnaires, :iii_18_1, :boolean
    add_column :questionnaires, :iii_18_2, :boolean
    add_column :questionnaires, :iii_18_3, :boolean
    add_column :questionnaires, :iii_18_4, :text
    add_column :questionnaires, :iii_23_4, :text
    add_column :questionnaires, :iii_24_1, :text
    add_column :questionnaires, :iii_25_1, :text
    add_column :questionnaires, :iii_28_1, :boolean
    add_column :questionnaires, :iii_28_2, :boolean
    add_column :questionnaires, :iii_28_3, :boolean
    add_column :questionnaires, :iii_28_4, :text
    add_column :questionnaires, :iii_29_1, :boolean
    add_column :questionnaires, :iii_29_2, :boolean
    add_column :questionnaires, :iii_29_3, :boolean
    add_column :questionnaires, :iii_29_4, :text
    add_column :questionnaires, :iii_30_1, :boolean
    add_column :questionnaires, :iii_30_2, :boolean
    add_column :questionnaires, :iii_30_3, :boolean
    add_column :questionnaires, :iii_30_4, :text
    add_column :questionnaires, :iii_31_1, :boolean
    add_column :questionnaires, :iii_31_2, :boolean
    add_column :questionnaires, :iii_31_3, :boolean
    add_column :questionnaires, :iii_31_4, :text
    add_column :questionnaires, :iii_32_1, :boolean
    add_column :questionnaires, :iii_32_2, :boolean
    add_column :questionnaires, :iii_32_3, :boolean
    add_column :questionnaires, :iii_32_4, :text
    add_column :questionnaires, :iii_33_1, :boolean
    add_column :questionnaires, :iii_33_2, :boolean
    add_column :questionnaires, :iii_33_3, :boolean
    add_column :questionnaires, :iii_33_4, :text
    add_column :questionnaires, :iii_38_9, :boolean
    add_column :questionnaires, :iii_43_1, :boolean
    add_column :questionnaires, :iii_43_2, :boolean
    add_column :questionnaires, :iii_43_3, :boolean
    add_column :questionnaires, :iii_43_4, :text
  end
end
