class AddPartIiiToQuestionnaires < ActiveRecord::Migration[5.2]
  def change
    add_column :questionnaires, :iii_1_1, :boolean
    add_column :questionnaires, :iii_1_2, :boolean
    add_column :questionnaires, :iii_1_3, :boolean
    add_column :questionnaires, :iii_1_4, :text
    add_column :questionnaires, :iii_2_1, :boolean
    add_column :questionnaires, :iii_2_2, :boolean
    add_column :questionnaires, :iii_2_3, :boolean
    add_column :questionnaires, :iii_2_4, :text
    add_column :questionnaires, :iii_3_1, :boolean
    add_column :questionnaires, :iii_3_2, :boolean
    add_column :questionnaires, :iii_3_3, :boolean
    add_column :questionnaires, :iii_3_4, :text
    add_column :questionnaires, :iii_4_1, :boolean
    add_column :questionnaires, :iii_4_2, :boolean
    add_column :questionnaires, :iii_4_3, :boolean
    add_column :questionnaires, :iii_4_4, :boolean
    add_column :questionnaires, :iii_4_5, :boolean
    add_column :questionnaires, :iii_4_6, :boolean
    add_column :questionnaires, :iii_4_7, :boolean
    add_column :questionnaires, :iii_4_8, :boolean
    add_column :questionnaires, :iii_4_9, :boolean
    add_column :questionnaires, :iii_4_10, :boolean
    add_column :questionnaires, :iii_4_11, :boolean
    add_column :questionnaires, :iii_4_12, :boolean
    add_column :questionnaires, :iii_4_13, :boolean
    add_column :questionnaires, :iii_4_14, :boolean
    add_column :questionnaires, :iii_4_15, :boolean
    add_column :questionnaires, :iii_4_16, :boolean
    add_column :questionnaires, :iii_4_17, :boolean
    add_column :questionnaires, :iii_4_18, :boolean
    add_column :questionnaires, :iii_4_19, :boolean
    add_column :questionnaires, :iii_4_20, :boolean
    add_column :questionnaires, :iii_4_21, :boolean
    add_column :questionnaires, :iii_4_22, :boolean
    add_column :questionnaires, :iii_4_23, :boolean
    add_column :questionnaires, :iii_4_24, :boolean
    add_column :questionnaires, :iii_4_25, :boolean
    add_column :questionnaires, :iii_4_26, :boolean
    add_column :questionnaires, :iii_4_27, :boolean
    add_column :questionnaires, :iii_5_1, :boolean
    add_column :questionnaires, :iii_5_2, :boolean
    add_column :questionnaires, :iii_5_3, :boolean
    add_column :questionnaires, :iii_5_4, :boolean
    add_column :questionnaires, :iii_5_5, :boolean
    add_column :questionnaires, :iii_5_6, :boolean
    add_column :questionnaires, :iii_6_1, :boolean
    add_column :questionnaires, :iii_6_2, :boolean
    add_column :questionnaires, :iii_6_3, :boolean
    add_column :questionnaires, :iii_6_4, :boolean
    add_column :questionnaires, :iii_6_5, :boolean
    add_column :questionnaires, :iii_6_6, :boolean
    add_column :questionnaires, :iii_6_7, :boolean
    add_column :questionnaires, :iii_6_8, :boolean
    add_column :questionnaires, :iii_6_9, :boolean
    add_column :questionnaires, :iii_6_10, :boolean
    add_column :questionnaires, :iii_6_11, :boolean
    add_column :questionnaires, :iii_6_12, :boolean
    add_column :questionnaires, :iii_6_13, :boolean
    add_column :questionnaires, :iii_7_1, :boolean
    add_column :questionnaires, :iii_7_2, :boolean
    add_column :questionnaires, :iii_7_3, :boolean
    add_column :questionnaires, :iii_7_4, :boolean
    add_column :questionnaires, :iii_7_5, :boolean
    add_column :questionnaires, :iii_7_6, :boolean
    add_column :questionnaires, :iii_7_7, :boolean
    add_column :questionnaires, :iii_8_1, :boolean
    add_column :questionnaires, :iii_8_2, :boolean
    add_column :questionnaires, :iii_8_3, :boolean
    add_column :questionnaires, :iii_9_1, :boolean
    add_column :questionnaires, :iii_9_2, :boolean
    add_column :questionnaires, :iii_9_3, :boolean
    add_column :questionnaires, :iii_10_1, :boolean
    add_column :questionnaires, :iii_10_2, :boolean
    add_column :questionnaires, :iii_10_3, :boolean
    add_column :questionnaires, :iii_11_1, :boolean
    add_column :questionnaires, :iii_11_2, :boolean
    add_column :questionnaires, :iii_11_3, :boolean
    add_column :questionnaires, :iii_12_1, :boolean
    add_column :questionnaires, :iii_12_2, :boolean
    add_column :questionnaires, :iii_12_3, :boolean
    add_column :questionnaires, :iii_13_1, :boolean
    add_column :questionnaires, :iii_14_1, :boolean
    add_column :questionnaires, :iii_14_2, :boolean
    add_column :questionnaires, :iii_14_3, :boolean
    add_column :questionnaires, :iii_14_4, :boolean
    add_column :questionnaires, :iii_14_5, :boolean
    add_column :questionnaires, :iii_14_6, :boolean
    add_column :questionnaires, :iii_14_7, :boolean
    add_column :questionnaires, :iii_14_8, :boolean
    add_column :questionnaires, :iii_14_9, :boolean
    add_column :questionnaires, :iii_14_10, :boolean
    add_column :questionnaires, :iii_14_11, :boolean
    add_column :questionnaires, :iii_14_12, :boolean
    add_column :questionnaires, :iii_14_13, :boolean
    add_column :questionnaires, :iii_14_14, :boolean
    add_column :questionnaires, :iii_14_15, :boolean
    add_column :questionnaires, :iii_14_16, :boolean
    add_column :questionnaires, :iii_14_17, :boolean
    add_column :questionnaires, :iii_14_18, :boolean
    add_column :questionnaires, :iii_14_19, :boolean
    add_column :questionnaires, :iii_14_20, :boolean
    add_column :questionnaires, :iii_15_1, :boolean
    add_column :questionnaires, :iii_15_2, :boolean
    add_column :questionnaires, :iii_15_3, :boolean
    add_column :questionnaires, :iii_16_1, :boolean
    add_column :questionnaires, :iii_16_2, :boolean
    add_column :questionnaires, :iii_16_3, :boolean
    add_column :questionnaires, :iii_17_1, :boolean
    add_column :questionnaires, :iii_17_2, :boolean
    add_column :questionnaires, :iii_17_3, :boolean
    add_column :questionnaires, :iii_18_1, :boolean
    add_column :questionnaires, :iii_18_2, :boolean
    add_column :questionnaires, :iii_18_3, :boolean
    add_column :questionnaires, :iii_18_4, :boolean
    add_column :questionnaires, :iii_18_5, :boolean
    add_column :questionnaires, :iii_18_6, :boolean
    add_column :questionnaires, :iii_18_7, :boolean
    add_column :questionnaires, :iii_19_1, :boolean
    add_column :questionnaires, :iii_19_2, :boolean
    add_column :questionnaires, :iii_19_3, :boolean
    add_column :questionnaires, :iii_19_4, :boolean
    add_column :questionnaires, :iii_19_5, :boolean
    add_column :questionnaires, :iii_19_6, :boolean
    add_column :questionnaires, :iii_19_7, :boolean
    add_column :questionnaires, :iii_19_8, :boolean
    add_column :questionnaires, :iii_20_1, :boolean
    add_column :questionnaires, :iii_20_2, :boolean
    add_column :questionnaires, :iii_20_3, :boolean
    add_column :questionnaires, :iii_20_4, :boolean
    add_column :questionnaires, :iii_21_1, :boolean
    add_column :questionnaires, :iii_21_2, :boolean
    add_column :questionnaires, :iii_21_3, :boolean
    add_column :questionnaires, :iii_21_4, :boolean
    add_column :questionnaires, :iii_22_1, :boolean
    add_column :questionnaires, :iii_22_2, :boolean
    add_column :questionnaires, :iii_22_3, :boolean
    add_column :questionnaires, :iii_22_4, :text
    add_column :questionnaires, :iii_23_1, :boolean
    add_column :questionnaires, :iii_23_2, :boolean
    add_column :questionnaires, :iii_23_3, :boolean
    add_column :questionnaires, :iii_23_4, :text
  end
end
