class AddFinalPartIToQuestionnaires < ActiveRecord::Migration[5.2]
  def change
    add_column :questionnaires, :i_4_1, :boolean
    add_column :questionnaires, :i_4_2, :boolean
    add_column :questionnaires, :i_4_3, :boolean
    add_column :questionnaires, :i_4_4, :boolean
    add_column :questionnaires, :i_4_5, :boolean
    add_column :questionnaires, :i_4_6, :boolean
    add_column :questionnaires, :i_4_7, :boolean
    add_column :questionnaires, :i_4_8, :boolean
    add_column :questionnaires, :i_4_9, :boolean
    add_column :questionnaires, :i_4_10, :boolean
    add_column :questionnaires, :i_4_11, :boolean
    add_column :questionnaires, :i_4_12, :boolean
    add_column :questionnaires, :i_4_13, :boolean
    add_column :questionnaires, :i_5_1, :boolean
    add_column :questionnaires, :i_5_2, :boolean
    add_column :questionnaires, :i_5_3, :boolean
    add_column :questionnaires, :i_5_4, :boolean
    add_column :questionnaires, :i_5_5, :boolean
    add_column :questionnaires, :i_5_6, :boolean
    add_column :questionnaires, :i_5_7, :boolean
    add_column :questionnaires, :i_5_8, :boolean
    add_column :questionnaires, :i_5_9, :boolean
    add_column :questionnaires, :i_5_10, :boolean
    add_column :questionnaires, :i_5_11, :boolean
    add_column :questionnaires, :i_5_12, :boolean
    add_column :questionnaires, :i_5_13, :boolean
    add_column :questionnaires, :i_5_14, :boolean
    add_column :questionnaires, :i_5_15, :boolean
    add_column :questionnaires, :i_5_16, :boolean
    add_column :questionnaires, :i_5_17, :boolean
    add_column :questionnaires, :i_5_18, :boolean
    add_column :questionnaires, :i_5_19, :boolean
    add_column :questionnaires, :i_5_20, :boolean
    add_column :questionnaires, :i_6_1, :boolean
    add_column :questionnaires, :i_6_2, :boolean
    add_column :questionnaires, :i_6_3, :boolean
    add_column :questionnaires, :i_7_1, :boolean
    add_column :questionnaires, :i_7_2, :boolean
    add_column :questionnaires, :i_7_3, :boolean
    add_column :questionnaires, :i_8_1, :boolean
    add_column :questionnaires, :i_8_2, :boolean
    add_column :questionnaires, :i_8_3, :boolean
    add_column :questionnaires, :i_8_4, :boolean
    add_column :questionnaires, :i_8_5, :boolean
    add_column :questionnaires, :i_8_6, :boolean
    add_column :questionnaires, :i_8_7, :boolean
    add_column :questionnaires, :i_8_8, :boolean
    add_column :questionnaires, :i_8_9, :boolean
    add_column :questionnaires, :i_8_10, :boolean
    add_column :questionnaires, :i_8_11, :boolean
    add_column :questionnaires, :i_9_1, :boolean
    add_column :questionnaires, :i_9_2, :boolean
    add_column :questionnaires, :i_9_3, :boolean
    add_column :questionnaires, :i_9_4, :boolean
    add_column :questionnaires, :i_9_5, :boolean
    add_column :questionnaires, :i_9_6, :boolean
    add_column :questionnaires, :i_10_1, :text
    add_column :questionnaires, :i_11_1, :text
    add_column :questionnaires, :i_12_1, :boolean
    add_column :questionnaires, :i_12_2, :boolean
    add_column :questionnaires, :i_12_3, :boolean
    add_column :questionnaires, :i_13_1, :boolean
    add_column :questionnaires, :i_13_2, :boolean
    add_column :questionnaires, :i_13_3, :boolean
    add_column :questionnaires, :i_14_1, :boolean
    add_column :questionnaires, :i_14_2, :boolean
    add_column :questionnaires, :i_14_3, :boolean
    add_column :questionnaires, :i_15_1, :boolean
    add_column :questionnaires, :i_15_2, :boolean
    add_column :questionnaires, :i_15_3, :boolean
    add_column :questionnaires, :i_16_1, :boolean
    add_column :questionnaires, :i_16_2, :boolean
    add_column :questionnaires, :i_16_3, :boolean
  end
end
