class AddPartIToQuestionnaires < ActiveRecord::Migration[5.2]
  def change
    add_column :questionnaires, :i_1_1, :boolean
    add_column :questionnaires, :i_1_2, :boolean
    add_column :questionnaires, :i_1_3, :boolean
    add_column :questionnaires, :i_1_4, :boolean
    add_column :questionnaires, :i_1_5, :boolean
    add_column :questionnaires, :i_1_6, :boolean
    add_column :questionnaires, :i_1_7, :boolean
    add_column :questionnaires, :i_1_8, :boolean
    add_column :questionnaires, :i_1_9, :boolean
    add_column :questionnaires, :i_1_10, :boolean
    add_column :questionnaires, :i_1_11, :boolean
    add_column :questionnaires, :i_2_1, :boolean
    add_column :questionnaires, :i_2_2, :boolean
    add_column :questionnaires, :i_2_3, :boolean
    add_column :questionnaires, :i_2_4, :boolean
    add_column :questionnaires, :i_2_5, :boolean
    add_column :questionnaires, :i_2_6, :boolean
    add_column :questionnaires, :i_2_7, :boolean
    add_column :questionnaires, :i_2_8, :boolean
    add_column :questionnaires, :i_2_9, :boolean
    add_column :questionnaires, :i_2_10, :boolean
    add_column :questionnaires, :i_2_11, :boolean
    add_column :questionnaires, :i_2_12, :boolean
    add_column :questionnaires, :i_2_13, :boolean
    add_column :questionnaires, :i_3_1, :boolean
    add_column :questionnaires, :i_3_2, :boolean
    add_column :questionnaires, :i_3_3, :boolean
    add_column :questionnaires, :i_3_4, :boolean
    add_column :questionnaires, :i_3_5, :boolean
    add_column :questionnaires, :i_3_6, :boolean
    add_column :questionnaires, :i_3_7, :boolean
    add_column :questionnaires, :i_3_8, :boolean
    add_column :questionnaires, :i_3_9, :boolean
    add_column :questionnaires, :i_3_10, :boolean
    add_column :questionnaires, :i_3_11, :boolean
  end
end
